# Generated by Django 2.0 on 2019-06-13 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='filemodel',
            name='more',
            field=models.TextField(default='...', max_length=200, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='filemodel',
            name='file',
            field=models.FileField(upload_to='file_center/', verbose_name='文件路径'),
        ),
        migrations.AlterField(
            model_name='filemodel',
            name='title',
            field=models.CharField(max_length=50, verbose_name='文件标题'),
        ),
        migrations.AlterField(
            model_name='filemodel',
            name='upload_time',
            field=models.DateTimeField(auto_now=True, verbose_name='上传时间'),
        ),
    ]
