# Generated by Django 2.0 on 2019-05-20 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('read_statistics', '0003_auto_20190508_1444'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='readdetail',
            options={'verbose_name': '单篇阅读计数库', 'verbose_name_plural': '单篇阅读计数库'},
        ),
        migrations.AlterModelOptions(
            name='readnum',
            options={'verbose_name': '总阅读计数库', 'verbose_name_plural': '总阅读计数库'},
        ),
        migrations.AlterField(
            model_name='readdetail',
            name='read_num',
            field=models.IntegerField(default=0, verbose_name='阅读数'),
        ),
        migrations.AlterField(
            model_name='readnum',
            name='read_num',
            field=models.IntegerField(default=0, verbose_name='阅读数'),
        ),
    ]
