# Generated by Django 2.0 on 2019-05-21 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20190521_0956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='blog_cover',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='blog_img/%Y/%m/%d', verbose_name='博客封面'),
        ),
    ]
