# Generated by Django 2.0 on 2019-05-31 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20190531_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='avatar\\default_64.png', upload_to='avatar'),
        ),
    ]
