# Generated by Django 2.0 on 2019-06-12 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20190531_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='userimg',
            field=models.ImageField(blank=True, default='avatar\\default_64.png', null=True, upload_to='user_img', verbose_name='头像'),
        ),
    ]
